# Generated by Django 5.2.8 on 2025-12-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0002_remove_user_phone_user_schools_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schools',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Leave empty for Super Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('payroll', 'Payroll Manager'), ('staff', 'Staff')], max_length=20),
        ),
    ]
