# Generated by Django 6.0.6 on 2026-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('payroll', 'Payroll Manager'), ('staff', 'Staff'), ('bursar', 'Bursar')], max_length=20),
        ),
    ]
