# Generated by Django 5.2.8 on 2025-12-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0006_remove_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='students.classgrade'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='students.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.classgrade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.classgrade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
