# Generated by Django 5.2.8 on 2026-04-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0007_alter_classroom_class_grade_alter_classroom_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgrade',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='classgrade',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_grades', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='is_boarder',
            field=models.CharField(choices=[('yes', 'Boarder'), ('no', 'Day Scholar')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classgrade',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'class_grade', 'name')},
        ),
    ]
