# Generated by Django 6.0.6 on 2026-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_section',
        ),
        migrations.AddField(
            model_name='student',
            name='current_section',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.section'),
        ),
    ]
