# Generated by Django 6.0.6 on 2026-08-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_current_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
