# Generated by Django 5.2.8 on 2025-11-27 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom'),
        ('fees', '0002_initial'),
        ('students', '0004_classroom_studentprofile_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),

        migrations.RemoveField(
            model_name='feestructure',
            name='name',
        ),

        migrations.AddField(
            model_name='feestructure',
            name='classroom',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='academics.classroom'
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),

        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fee')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestructure')),
            ],
        ),

        migrations.AddField(
            model_name='feestructure',
            name='fee_items',
            field=models.ManyToManyField(through='fees.FeeStructureItem', to='fees.fee'),
        ),

        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),

        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='Cash', max_length=50)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.studentfee')),
            ],
        ),
    ]
