# Generated by Django 5.2.8 on 2025-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Term', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(default='2025'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
