# Generated by Django 5.2.8 on 2025-11-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_class_level_remove_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
