# Generated by Django 5.2.8 on 2026-04-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('exams', '0003_exam_date_exam_description_exam_exam_type_and_more'),
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student', 'subject')},
        ),
    ]
