# Generated by Django 5.2.8 on 2025-12-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('teachers', '0002_remove_teacher_name_teacher_assigned_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.subject'),
        ),
    ]
