# Generated by Django 5.2.8 on 2026-04-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('profiles', '0003_teacherprofile_school_teacherprofile_subjects'),
        ('schools', '0001_initial'),
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
        ('teachers', '0003_alter_teacher_assigned_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profiles.teacherprofile')),
            ],
            options={
                'ordering': ['classroom__class_grade__name', 'classroom__section__name', 'subject__name'],
                'unique_together': {('teacher', 'subject', 'classroom')},
            },
        ),
    ]
