# Generated by Django 5.2.8 on 2025-12-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='school',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='school',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarycomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('school', 'start_date', 'end_date')},
        ),
    ]
