# Generated by Django 5.2.8 on 2025-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('remark', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
    ]
