# Generated by Django 5.2.8 on 2026-04-28 17:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('profiles', '0003_teacherprofile_school_teacherprofile_subjects'),
        ('schools', '0001_initial'),
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.teacherprofile'),
        ),
        migrations.CreateModel(
            name='TimetableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(default=list)),
                ('lesson_minutes', models.PositiveIntegerField(default=45)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='16:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_settings', to='students.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_settings', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_lessons', models.PositiveIntegerField(default=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='timetable.timetablesetting')),
            ],
        ),
        migrations.CreateModel(
            name='FixedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lessons', to='timetable.timetablesetting')),
            ],
        ),
        migrations.CreateModel(
            name='BreakPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timetable.timetablesetting')),
            ],
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetablesetting'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='period',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
