# Generated by Django 5.2.8 on 2026-05-07 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('profiles', '0003_teacherprofile_school_teacherprofile_subjects'),
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
        ('teachers', '0004_teachersubjectassignment'),
        ('timetable', '0002_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakPeriod',
            new_name='TimetableBreak',
        ),
        migrations.RemoveField(
            model_name='subjectrule',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='subjectrule',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='timetablebreak',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timetablesetting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='is_fixed',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='setting',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='break_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetablesetting',
            name='auto_generate',
            field=models.BooleanField(default=True, help_text='Automatically generate timetable'),
        ),
        migrations.AddField(
            model_name='timetablesetting',
            name='lesson_duration',
            field=models.PositiveIntegerField(default=45, help_text='Lesson duration in minutes'),
        ),
        migrations.AddField(
            model_name='timetablesetting',
            name='spread_lessons_evenly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='students.classroom'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='timetablesetting',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_setting', to='students.classroom'),
        ),
        migrations.AlterField(
            model_name='timetablesetting',
            name='days',
            field=models.JSONField(default=list, help_text="Example: ['Monday', 'Tuesday', 'Wednesday']"),
        ),
        migrations.CreateModel(
            name='SubjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveIntegerField(default=4)),
                ('fixed_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True)),
                ('fixed_start_time', models.TimeField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='timetable.timetablesetting')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachersubjectassignment')),
            ],
            options={
                'unique_together': {('setting', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='FixedLesson',
        ),
        migrations.DeleteModel(
            name='SubjectRule',
        ),
        migrations.RemoveField(
            model_name='timetablesetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='timetablesetting',
            name='lesson_minutes',
        ),
        migrations.RemoveField(
            model_name='timetablesetting',
            name='school',
        ),
    ]
