# Generated by Django 6.0.6 on 2026-06-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('timetable', '0005_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.school'),
        ),
    ]
