# Generated by Django 6.0.6 on 2026-06-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_school_subject_school_and_more'),
        ('profiles', '0003_teacherprofile_school_teacherprofile_subjects'),
        ('schools', '0001_initial'),
        ('students', '0008_alter_classgrade_options_alter_section_options_and_more'),
        ('timetable', '0006_alter_period_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('lesson_duration', models.PositiveIntegerField(default=45, help_text='Duration of each lesson in minutes')),
                ('school_start_time', models.TimeField(default='08:00', help_text='Time the first lesson starts')),
                ('school_end_time', models.TimeField(default='15:45', help_text='Time the last lesson ends')),
                ('days', models.JSONField(default=list, help_text="['Monday','Tuesday','Wednesday','Thursday','Friday']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_configs', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='GenerationBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timetable.timetablegenerationconfig')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('entries_created', models.PositiveIntegerField(default=0)),
                ('conflicts', models.JSONField(default=list)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveIntegerField(default=4)),
                ('is_fixed', models.BooleanField(default=False)),
                ('fixed_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True)),
                ('fixed_start_time', models.TimeField(blank=True, null=True)),
                ('fixed_scope', models.CharField(choices=[('classroom', 'Per Classroom'), ('school', 'School-wide')], default='classroom', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='students.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.teacherprofile')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='timetable.timetablegenerationconfig')),
            ],
            options={
                'unique_together': {('config', 'classroom', 'subject')},
            },
        ),
    ]
