# Generated by Django 5.2.8 on 2025-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_enrollment_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
