# Generated by Django 5.2.8 on 2025-12-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom'),
        ('schools', '0001_initial'),
        ('students', '0006_remove_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.classgrade'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='academics.subject'),
        ),
    ]
